# Generated by core/agent/packaging/ship-tap.sh — do not hand-edit.
# Prebuilt `agentastic` binary from the //core/agent Rust workspace, installed as `agentastic`,
# alongside the `agentastic-code-mode-host` helper it spawns for Code Mode.
class Agentastic < Formula
  desc "Agentastic coding agent CLI"
  homepage "https://www.agentastic.dev"
  version "0.14.0"
  license "Apache-2.0"

  BASE = "https://releases.agentastic.ai/agent/v0.14.0".freeze

  on_macos do
    on_arm do
      url "#{BASE}/agentastic-0.14.0-aarch64-apple-darwin.tar.gz"
      sha256 "c940f99e48539d390e177729257054ed331487fe8e9f4df359256afcc9a37783"
    end
    on_intel do
      url "#{BASE}/agentastic-0.14.0-x86_64-apple-darwin.tar.gz"
      sha256 "c4aef518d6d4c5ae7f663c578e290ee02a995ff3edbeb08d595df1000e961301"
    end
  end

  on_linux do
    on_arm do
      url "#{BASE}/agentastic-0.14.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6b2f4c871cc02b86c74162bac7c9594d6ee533874a1642f8bc212af4b746250f"
    end
    on_intel do
      url "#{BASE}/agentastic-0.14.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2c18fd23f30dddf225dd9cd42ddee686818fd7ee0be906cd9450269569c49c9b"
    end
  end

  def install
    # Tarball holds two stripped binaries: the CLI and the code-mode host, which the
    # CLI spawns from its own bin dir under that exact name. The background daemon
    # installs its app server only from a complete package (both binaries plus this
    # metadata), so keep them together in libexec, apart from the keg's receipts.
    (libexec/"bin").install "agentastic", "agentastic-code-mode-host"
    triple = "#{Hardware::CPU.arm? ? "aarch64" : "x86_64"}-#{OS.mac? ? "apple-darwin" : "unknown-linux-gnu"}"
    (libexec/"agentastic-package.json").write <<~JSON
      {"layoutVersion":1,"version":"#{version}","target":"#{triple}","variant":"agentastic","entrypoint":"bin/agentastic","resourcesDir":"agentastic-resources","pathDir":"agentastic-path"}
    JSON
    bin.install_symlink libexec/"bin/agentastic" => "agentastic"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentastic --version")
  end
end
