# Generated by core/agent/packaging/ship-tap.sh — do not hand-edit.
# Prebuilt `codex` binary from the //core/agent Rust workspace, installed as `agentastic`,
# alongside the `agentastic-code-mode-host` helper it spawns for Code Mode.
class Agentastic < Formula
  desc "Agentastic coding agent CLI"
  homepage "https://www.agentastic.dev"
  version "0.13.0"
  license "Apache-2.0"

  BASE = "https://releases.agentastic.ai/agent/v0.13.0".freeze

  on_macos do
    on_arm do
      url "#{BASE}/agentastic-0.13.0-aarch64-apple-darwin.tar.gz"
      sha256 "c290dc747e4a2d148be58581eeeee00c152f4c12ed5c462941863973e01e85e0"
    end
    on_intel do
      url "#{BASE}/agentastic-0.13.0-x86_64-apple-darwin.tar.gz"
      sha256 "b933494171dc436daf096f3802e2406a95d56a77fcac3d0b7513ed38cc0adb6c"
    end
  end

  on_linux do
    on_arm do
      url "#{BASE}/agentastic-0.13.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d4836f071702838d6432cd707112c0b8f5d3abd7d5e765bc53529ab9152f45bf"
    end
    on_intel do
      url "#{BASE}/agentastic-0.13.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c757c397f2c288b8ad40f6017d5250522d5ec849f8e7f8a69b954d83f731b4ec"
    end
  end

  def install
    # Tarball holds two stripped binaries: the CLI, exposed as `agentastic`, and the
    # code-mode host, which the CLI spawns from its own bin dir under that exact
    # name. Installing only the CLI leaves Code Mode unavailable.
    bin.install "codex" => "agentastic"
    bin.install "agentastic-code-mode-host"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentastic --version")
  end
end
