# Generated by core/agent/packaging/ship-tap.sh — do not hand-edit.
# Prebuilt `codex` binary from the //core/agent Rust workspace, installed as `agentastic`.
class Agentastic < Formula
  desc "Agentastic coding agent CLI"
  homepage "https://www.agentastic.dev"
  version "0.11.1"
  license "Apache-2.0"

  BASE = "https://releases.agentastic.ai/agent/v0.11.1".freeze

  on_macos do
    on_arm do
      url "#{BASE}/agentastic-0.11.1-aarch64-apple-darwin.tar.gz"
      sha256 "f95ee5a48a92578ee40ed2bce1bde60f5cab6514455415e6e426ef48a8a9f7ee"
    end
    on_intel do
      url "#{BASE}/agentastic-0.11.1-x86_64-apple-darwin.tar.gz"
      sha256 "7af62e2588a5ff5aea73e6d7348412f9fba807ff87c90e265e06d30f5d2bdc84"
    end
  end

  on_linux do
    on_arm do
      url "#{BASE}/agentastic-0.11.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "6b6472ab25c7d62444337e7f297d8b8bcdb128a8f6f097ea385c37bc75b57b6c"
    end
    on_intel do
      url "#{BASE}/agentastic-0.11.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f4b00e38f11f63c6ac082eaf118d12f946b8a3975167522c87641fe7fc243b2c"
    end
  end

  def install
    # Tarball holds a single stripped `codex` binary; expose it as `agentastic`.
    bin.install "codex" => "agentastic"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentastic --version")
  end
end
