# Generated by core/agent/packaging/write-formula.py — do not hand-edit.
# Prebuilt `agentastic` binary from the //core/agent Rust workspace, installed as `agentastic`,
# alongside the `agentastic-code-mode-host` helper it spawns for Code Mode. Release train: beta.
class AgentasticBeta < Formula
  desc "Agentastic coding agent CLI (beta channel)"
  homepage "https://www.agentastic.dev"
  version "0.16.0"
  license "Apache-2.0"

  BASE = "https://releases.agentastic.ai/agent/v0.16.0".freeze

  # Homebrew loads every declared conflict, even when it is not installed. Only
  # inspect active kegs so upgrading one trusted train does not require trusting
  # the other trains (or loading a nightly formula that has not been published).
  ["agentastic", "agentastic-nightly"].each do |name|
    next unless (HOMEBREW_PREFIX/"var/homebrew/linked"/name).exist? && (HOMEBREW_PREFIX/"opt"/name).exist?

    conflicts_with "agentasticai/tap/#{name}",
      because: "every Agentastic release train installs the `agentastic` command"
  end

  on_macos do
    on_arm do
      url "#{BASE}/agentastic-0.16.0-aarch64-apple-darwin.tar.gz"
      sha256 "fb04a867779e8c1a83e94569b57511e05d6d46317370a9de0616cdc52d34668d"
    end
    on_intel do
      url "#{BASE}/agentastic-0.16.0-x86_64-apple-darwin.tar.gz"
      sha256 "67b03cbdb6c42879dca47f6903d61556f8fa476bd98595d49997839935bf4ce5"
    end
  end

  on_linux do
    on_arm do
      url "#{BASE}/agentastic-0.16.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "7b075108ee64a48682aa21a5a76ec06a6dc4c26b8e3ffd5491e5f5a8e95ef5de"
    end
    on_intel do
      url "#{BASE}/agentastic-0.16.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6dc05d11c089e2f7560b4b2d9deaf6ecbe071b0ecce40033f7f4c8f92e0c7f65"
    end
  end

  def install
    # Tarball holds two stripped binaries: the CLI and the code-mode host, which the
    # CLI spawns from its own bin dir under that exact name. The background daemon
    # installs its app server only from a complete package (both binaries plus this
    # metadata), so keep them together in libexec, apart from the keg's receipts.
    # `channel` is the train `agentastic` keeps upgrading along.
    (libexec/"bin").install "agentastic", "agentastic-code-mode-host"
    triple = "#{Hardware::CPU.arm? ? "aarch64" : "x86_64"}-#{OS.mac? ? "apple-darwin" : "unknown-linux-gnu"}"
    (libexec/"agentastic-package.json").write <<~JSON
      {"layoutVersion":1,"version":"#{version}","target":"#{triple}","variant":"agentastic","entrypoint":"bin/agentastic","resourcesDir":"agentastic-resources","pathDir":"agentastic-path","channel":"beta"}
    JSON
    bin.install_symlink libexec/"bin/agentastic" => "agentastic"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentastic --version")
  end
end
