# Generated by core/agent/packaging/write-formula.py — do not hand-edit.
# Prebuilt `agentastic` binary from the //core/agent Rust workspace, installed as `agentastic`,
# alongside the `agentastic-code-mode-host` helper it spawns for Code Mode. Release train: beta.
class AgentasticBeta < Formula
  desc "Agentastic coding agent CLI (beta channel)"
  homepage "https://www.agentastic.dev"
  version "0.18.0"
  license "Apache-2.0"

  BASE = "https://releases.agentastic.ai/agent/v0.18.0".freeze

  # Homebrew loads every declared conflict, even when it is not installed. Only
  # inspect active kegs so upgrading one trusted train does not require trusting
  # the other trains (or loading a nightly formula that has not been published).
  ["agentastic", "agentastic-nightly"].each do |name|
    next unless (HOMEBREW_PREFIX/"var/homebrew/linked"/name).exist? && (HOMEBREW_PREFIX/"opt"/name).exist?

    conflicts_with "agentasticai/tap/#{name}",
      because: "every Agentastic release train installs the `agentastic` command"
  end

  on_macos do
    on_arm do
      url "#{BASE}/agentastic-0.18.0-aarch64-apple-darwin.tar.gz"
      sha256 "e88972360c9caec3618c83ddcb43bbeb755b85c1d4932ffbc5ded6d28fb45a93"
    end
    on_intel do
      url "#{BASE}/agentastic-0.18.0-x86_64-apple-darwin.tar.gz"
      sha256 "14ee9fff2c100a4f06e5fd18028f828ac5436cc32c3e77aebcb3e9dabfd7b41a"
    end
  end

  on_linux do
    on_arm do
      url "#{BASE}/agentastic-0.18.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "77a9f807865132ac4a4d5f8af938b8aa58873336b45cd3075f407fc7ba764771"
    end
    on_intel do
      url "#{BASE}/agentastic-0.18.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ad3b5040b39b42e2c841064c633a827521f228543ebed5782a6400b38a4ce188"
    end
  end

  def install
    # Tarball holds two stripped binaries: the CLI and the code-mode host, which the
    # CLI spawns from its own bin dir under that exact name. The background daemon
    # installs its app server only from a complete package (both binaries plus this
    # metadata), so keep them together in libexec, apart from the keg's receipts.
    # `channel` is the train `agentastic` keeps upgrading along.
    (libexec/"bin").install "agentastic", "agentastic-code-mode-host"
    triple = "#{Hardware::CPU.arm? ? "aarch64" : "x86_64"}-#{OS.mac? ? "apple-darwin" : "unknown-linux-gnu"}"
    (libexec/"agentastic-package.json").write <<~JSON
      {"layoutVersion":1,"version":"#{version}","target":"#{triple}","variant":"agentastic","entrypoint":"bin/agentastic","resourcesDir":"agentastic-resources","pathDir":"agentastic-path","channel":"beta"}
    JSON
    bin.install_symlink libexec/"bin/agentastic" => "agentastic"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentastic --version")
  end
end
